#!/usr/bin/env bash

echo "Creating S3 bucket..."

# check for bucket name
if [ -z "$1" ]; then
    echo "There needs to be bucket name"
    exit 1
fi 

BUCKET_NAME=$1

aws s3api create-bucket \
  --bucket $BUCKET_NAME \
  --region ap-south-1 \
  --create-bucket-configuration LocationConstraint=ap-south-1
