#!/usr/bin/env bash

echo "Deploying CloudFormation template to create S3 bucket..."

STACK_NAME="s3-bucket-stack-$(date +%s)"

aws cloudformation deploy \
--template-file template.yaml \
--no-execute-changeset \
--region ap-south-1 \
--stack-name $STACK_NAME